# Generated by Django 4.1.5 on 2023-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=700)),
                ('ide', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Accueil',
                'verbose_name_plural': 'Accueils',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code_produit', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=30)),
                ('caracteristique', models.CharField(default='', max_length=450)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=30)),
                ('statut', models.CharField(max_length=30)),
                ('caracteristique', models.CharField(default='', max_length=450)),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=30)),
                ('caracteristique', models.CharField(default='', max_length=450)),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
            },
        ),
        migrations.CreateModel(
            name='Tissu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=30)),
                ('caracteristique', models.CharField(default='', max_length=450)),
            ],
            options={
                'verbose_name': 'Tissu',
                'verbose_name_plural': 'Tissus',
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('code', models.CharField(max_length=30)),
                ('statut', models.CharField(max_length=30)),
                ('caracteristique', models.CharField(default='', max_length=450)),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
            },
        ),
    ]
